### ISSUE TITLE
Feature: Bootstrap Modals for Validation Errors

### ISSUE THREAD

**Issue by MartinDevStudent** [MartinDevStudent/healthtrackerrest#109]
Alert windows are inconsistent with rest of application: implement [bootstrap modals](https://getbootstrap.com/docs/4.0/components/modal/) where alert windows are currently being used

- [x] #110
- [x] home-page (Included in #110)
- [x] register-page (Included in #110)
- [x] #112
- [x] activity-profile (Included in #112)
- [x] #113
- [x] meal-overview (Included in #113)
- [x] meal-profile (Included in #113)
- [x] #115
- [x] #116
- [x] user-profile (included in  #116)
